use
booking_hotel;

INSERT INTO location(code, name)
VALUES
    ('AN-GIANG', 'An Giang'),
    ('BA-RIA-VUNG-TAU', 'Bà Rịa - Vũng Tàu'),
    ('BAC-GIANG', 'Bắc Giang'),
    ('BAC-KAN', 'Bắc Kạn'),
    ('BAC-LIEU', 'Bạc Liêu'),
    ('BAC-NINH', 'Bắc Ninh'),
    ('BEN-TRE', 'Bến Tre'),
    ('BINH-DINH', 'Bình Định'),
    ('BINH-DUONG', 'Bình Dương'),
    ('BINH-PHUOC', 'Bình Phước'),
    ('BINH-THUAN', 'Bình Thuận'),
    ('CA-MAU', 'Cà Mau'),
    ('CAO-BANG', 'Cao Bằng'),
    ('DA-NANG', 'Đà Nẵng'),
    ('DAK-LAK', 'Đắk Lắk'),
    ('DAK-NONG', 'Đắk Nông'),
    ('DIEN-BIEN', 'Điện Biên'),
    ('DONG-NAI', 'Đồng Nai'),
    ('DONG-THAP', 'Đồng Tháp'),
    ('GIA-LAI', 'Gia Lai'),
    ('HA-GIANG', 'Hà Giang'),
    ('HA-NAM', 'Hà Nam'),
    ('HA-NOI', 'Hà Nội'),
    ('HA-TAY', 'Hà Tây'),
    ('HA-TINH', 'Hà Tĩnh'),
    ('HAI-DUONG', 'Hải Dương'),
    ('HAI-PHONG', 'Hải Phòng'),
    ('HO-CHI-MINH', 'Hồ Chí Minh'),
    ('HOA-BINH', 'Hòa Bình'),
    ('HOA-BINH', 'Hòa Bình'),
    ('HUNG-YEN', 'Hưng Yên'),
    ('KHANH-HOA', 'Khánh Hòa'),
    ('KIEN-GIANG', 'Kiên Giang'),
    ('KON-TUM', 'Kon Tum'),
    ('LAI-CHAU', 'Lai Châu'),
    ('LAM-DONG', 'Lâm Đồng'),
    ('LANG-SON', 'Lạng Sơn'),
    ('LAO-CAI', 'Lào Cai'),
    ('LONG-AN', 'Long An'),
    ('NAM-DINH', 'Nam Định'),
    ('NGHE-AN', 'Nghệ An'),
    ('NINH-BINH', 'Ninh Bình'),
    ('NINH-THUAN', 'Ninh Thuận'),
    ('PHU-THO', 'Phú Thọ'),
    ('PHU-YEN', 'Phú Yên'),
    ('QUANG-BINH', 'Quảng Bình'),
    ('QUANG-NAM', 'Quảng Nam'),
    ('QUANG-NGAI', 'Quảng Ngãi'),
    ('QUANG-NINH', 'Quảng Ninh'),
    ('QUANG-TRI', 'Quảng Trị'),
    ('SOC-TRANG', 'Sóc Trăng'),
    ('SON-LA', 'Sơn La'),
    ('TAY-NINH', 'Tây Ninh'),
    ('THAI-BINH', 'Thái Bình'),
    ('THAI-NGUYEN', 'Thái Nguyên'),
    ('THANH-HOA', 'Thanh Hóa'),
    ('THUA-THIEN-HUE', 'Thừa Thiên Huế'),
    ('TIEN-GIANG', 'Tiền Giang'),
    ('TRA-VINH', 'Trà Vinh'),
    ('TUYEN-QUANG', 'Tuyên Quang'),
    ('VINH-LONG', 'Vĩnh Long'),
    ('VINH-PHUC', 'Vĩnh Phúc'),
    ('YEN-BAI', 'Yên Bái');